#!/bin/bash
# https://github.com/ekaf/ski/ili2map
# (c)2017-21 Eric Kafe, CC BY 4.0, https://creativecommons.org/licenses/by/4.0/

LC_ALL=C

db=ski-pwn

#ILI file:
v=30
iliz=ski-ili$v.txt.gz

if [ ! -f $db-flat.txt ]
then
echo Running pwn2flat, to produce the needed $db-flat.txt file
`pwd`/pwn2flat
fi

echo Map ILI ids to all Princeton WordNet versions:
cat $iliz|
gunzip|
join - $db-flat.txt|
awk '{print$2,$3}'|
sort -u|
sort -t: -k1,1|
tee $db-ili-map.txt|
awk '{a[$1]=$2}
END{
#Map ILI ids to their last known Princeton WordNet version:
for(x in a)print x,a[x]
}'|
sort -k1,1 > $db-ili-last.txt
