#!/bin/bash
# mcr2free (c) 2017 Eric Kafe
# license CC BY 4.0, https://creativecommons.org/licenses/by/4.0/

# MCR version:
v=30
dbz=ski-mcr$v-2016.txt.gz

echo Making Freeling sense databases, this may take a few minutes...
cat $dbz|gunzip|awk -f mcr2free.awk v=$v
