#!/bin/bash
# pwn2flat (c) 2017 Eric Kafe
# license CC BY 4.0, https://creativecommons.org/licenses/by/4.0/

db=ski-pwn
dbp=`echo -n $db|tr -d "-"`

echo Flat text relation between all synsets in all WordNet versions and their sense keys
cat $db-sets.txt.gz|gunzip|awk -f pwn2flat.awk db=$db dbp=$dbp > $db-flat.txt
