#!/bin/bash
# pwn2maps (c) 2017 Eric Kafe
# license CC BY 4.0, https://creativecommons.org/licenses/by/4.0/

db=ski-pwn

echo Extracting all WordNet synset offset mappings, this may take a few minutes...
cat $db-sets.txt.gz|gunzip|awk -f pwn2maps.awk db=$db
