#!/bin/bash
# https://github.com/ekaf/ski/wn2ski
# (c)2017 Eric Kafe, CC BY 4.0, https://creativecommons.org/licenses/by/4.0/

LC_ALL=C

db=ski-pwn

echo Building Sense Key Index, this may take a few minutes...

# Input files: the index.sense file from each version of
# the original WordNet ( http://wordnetcode.princeton.edu),
# stored in a subdirectory named dict-WordnetVersion.Number.
# Version 3.1.1 is "Wordnet for SQL", retrieved from
# http://wordnetcode.princeton.edu/wn_for_sql.tar.gz

awk -f wn2ski.awk In/dict-{1.5,1.6,1.7,1.7.1,2.0,2.1,3.0,3.1,3.1.1}/index.sense|\
sort -k1,1|
gzip > $db-sets.txt.gz
